FROM jenkins/jenkins:lts
#ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
#COPY 001_setup.groovy /usr/share/jenkins/ref/init.groovy.d/001_setup.groovy
#COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
#RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
